### goal
# Stage 1: Chinese → Braille (bidirectional c2b)

### model
model_name_or_path: saves/Qwen2.5-7B-Instruct-Braille/7B_sentence_10pc_qwen2.5i_train_fullsft_0731_v1/checkpoint-26023
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
bf16: true
deepspeed: train_config/deepspeed/ds_z3_config.json  

### dataset
# Use dataset keys defined in data/dataset_info.json
dataset: bidirectional_c2b_sentence_train_20251030,bidirectional_c2b_passage_train_20251030
template: qwen
cutoff_len: 2048 
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: saves/Qwen2.5-7B-Instruct-Braille/bidir_v1_20251030_stage1_c2b
logging_steps: 10
save_steps: 500
plot_loss: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 4.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
ddp_timeout: 180000000
train_on_prompt: false
report_to: swanlab
flash_attn: auto
disable_shuffling: false   

### eval
eval_dataset: bidirectional_c2b_sentence_validation_20251030,bidirectional_c2b_passage_validation_20251030
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
do_eval: true